name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/scientificcomputing/fenics-gmsh:2023-02-20
    steps:
      - uses: actions/checkout@v3

      - name: Cache
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/instant
            ~/.cache/dijitso
            ~/.cache/pip
            /__w/pulse/pulse/_build/jupyter_execute
          key: cache_v5
          restore-keys: |
            cache_v5

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          make dev

      - name: Build docs
        run: |
          make docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
